image: docker:1.11

services:
    - docker:dind

stages:
    - build
    - test
    - deploy

before_script:
    - docker version

build:
    stage: build
    script:
        - docker build -t napi .

test:
    stage: test
    script:
        - apk add --no-cache py-pip
        - pip install docker-compose
        - cd tests && /usr/bin/docker-compose build napitester
        - cd tests && ./run_unit_tests.sh

deploy:
    stage: deploy
    script:
        - echo "no deployment support yet!"
