image: docker:1.11

services:
    - docker:dind

stages:
    - build
    - test
    - deploy

before_script:
    - docker version

build:
    stage: build
    script:
        - docker build -t napi .

test:
    stage: test
    script:
        - apk add --no-cache py-pip
        - apk add --no-cache bash
        - pip install docker-compose
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - docker pull registry.gitlab.com/hesperos/napi/napitester
        - docker tag registry.gitlab.com/hesperos/napi/napitester napitester
        - cd tests && ./run_unit_tests.sh
    artifacts:
        paths:
            - tests/coverage/

deploy:
    stage: deploy
    script:
        - echo "no deployment support yet!"
