#!/bin/bash

# force indendation settings
# vim: ts=4 shiftwidth=4 expandtab

read -r -d '' h1 << HELP1
BusyBox v1.18.5 (Ubuntu 1:1.18.5-1ubuntu4.1) multi-call binary.

Usage: wget [-c|--continue] [-s|--spider] [-q|--quiet] [-O|--output-document FILE]
	[--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
	[--no-check-certificate] [-U|--user-agent AGENT] URL

Retrieve files via HTTP or FTP

Options:
	-s	Spider mode - only check file existence
	-c	Continue retrieval of aborted transfer
	-q	Quiet
HELP1


read -r -d '' h2 << HELP2
	-P DIR	Save to DIR (default .)
	-O FILE	Save to FILE ('-' for stdout)
	-U STR	Use STR for User-Agent header
	-Y	Use proxy ('on' or 'off')
HELP2

echo "$h1"

if [ ${SUPPORT_S:-0} -eq 1 ]; then
	echo "  -S,  --server-response         print server response."
fi

if [ ${SUPPORT_POST:-0} -eq 1 ]; then
       echo " --post-data=STRING	  use the POST method; send STRING as the data.  "
       echo " --post-file=FILE		use the POST method; send contents of FILE.  "
fi

touch /tmp/cipka

echo "$h2"
