FROM ubuntu:12.04

RUN apt-get update -y
RUN apt-get install -y \
        busybox \
        libssl-dev \
        make \
        bison \
        flex \
        patch \
        shunit2 \
        mplayer2 \
        mediainfo \
        ffmpeg \
        gcc-multilib \
        g++-multilib \
        ncurses-dev \
        libwww-perl \
        original-awk \
        p7zip-full \
        mawk \
        gawk \
        wget \
        automake \
        autoconf \
        make \
        texinfo \
        install-info

# kcov dependencies
RUN apt-get update -y
RUN apt-get install -y --fix-missing \
        pkg-config
RUN apt-get install -y \
        zlib1g \
        libcurl4-openssl-dev \
        libelf-dev \
        libdw-dev \
        cmake \
        cmake-data \
        binutils-dev \
        zlib1g-dev \
        python-minimal \
        git

ENV NAPITESTER_HOME /home/napitester
ENV NAPITESTER_BIN $NAPITESTER_HOME/bin
ENV INSTALL_DIR /tmp/install

RUN git clone https://github.com/SimonKagstrom/kcov.git $INSTALL_DIR/kcov && \
        cd $INSTALL_DIR/kcov && \
        git reset --hard v33 && \
        mkdir build && \
        cd build && \
        cmake .. && \
        make && \
        make install

RUN useradd -m -U napitester -d /home/napitester
RUN mkdir -p $INSTALL_DIR
WORKDIR $INSTALL_DIR

ADD napitester $INSTALL_DIR/napitester
RUN ./napitester/prepare_shells.pl
RUN ./napitester/prepare_assets.pl

WORKDIR $NAPITESTER_HOME
USER napitester
RUN mkdir -p $NAPITESTER_BIN
