FROM ubuntu:14.04

RUN apt-get update -y
RUN apt-get install -y \
        busybox \
        libssl-dev \
        bison \
        flex \
        patch \
        shunit2 \
        mplayer2 \
        mediainfo \
        libav-tools \
        gcc-multilib \
        g++-multilib \
        ncurses-dev \
        libwww-perl \
        original-awk \
        p7zip-full \
        mawk \
        gawk \
        wget \
        automake \
        autoconf \
        make \
        texinfo \
        install-info

# set-up environment
ENV NAPITESTER_HOME /home/napitester
ENV NAPITESTER_BIN $NAPITESTER_HOME/bin
ENV NAPITESTER_OPT /opt/napi
ENV NAPITESTER_TESTDATA $NAPITESTER_OPT/testdata
ENV NAPITESTER_SHELLS $NAPITESTER_OPT/bash
ENV INSTALL_DIR /tmp/install

RUN useradd -m -U napitester -d $NAPITESTER_HOME
RUN mkdir -p $INSTALL_DIR

# kcov dependencies
RUN apt-get install -y --fix-missing \
        pkg-config

RUN apt-get install -y \
        zlib1g \
        libcurl4-openssl-dev \
        libelf-dev \
        libdw-dev \
        cmake \
        cmake-data \
        binutils-dev \
        zlib1g-dev \
        python-minimal

# scpmocker dependencies
RUN apt-get install -y \
        python-pip \
        python-setuptools

# setup shells and test assets
ADD napitester $INSTALL_DIR/napitester
WORKDIR $INSTALL_DIR
RUN ./napitester/prepare_kcov.pl
RUN ./napitester/prepare_scpmocker.pl
RUN ./napitester/prepare_shells.pl $NAPITESTER_SHELLS
RUN ./napitester/prepare_assets.pl $NAPITESTER_TESTDATA

# switch to test user
WORKDIR $NAPITESTER_HOME
USER napitester
RUN mkdir -p $NAPITESTER_BIN
