.\" man page originally for the Debian/GNU Linux system
.TH NAPI "1" "February 2015" "napi: 1.3.4" "User Commands"
.SH NAME
napi \- napiprojekt client written in bash
.SH DESCRIPTION
napi [\fBoptions\fR] [\fIfile\fR|\fIdirectory\fR|\fI*\fR]
.PP
Options:
.TP
\fB\-a\fR or \fB\-\-abbrev\fR [\fIstring\fR]
Add some string before the the extension, for example: name.\fIstring\fR.txt .
.TP
\fB\-b\fR or \fB\-\-bigger\-than\fR [\fIsize MiB\fR]
Search for subtitles only for files which size is larger that \fIsize\fR.
.TP
\fB\-c\fR or \fB\-\-cover\fR
Fetch the cover.
.TP
\fB\-C\fR or \fB\-\-charset\fR
Convert file encoding. Use \fB\iconv \-l\fR to see all available encodings.
.TP
\fB\-e\fR or \fB\-\-ext\fR
Change the file extension, defaults to \fI.txt\fI
.TP
\fB\-F\fR or \fB\-\-forks\fR [\fInumber\fR]
Set the number of parallel processes, defaults to \fI4\fR.
.TP
\fB\-I\fR or \fB\-\-id\fR [\fIpynapi\fR|\fIother\fR|\fINapiProjektPython\fR|\fINapiProjekt\fR]
Determine how to identify yourself while connecting to napiprojekt.pl servers, defaults to \fINapiProjektPython\fR.
.TP
\fB\-l\fR or \fB\-\-log\fR [\fIlogfile\fR]
Log output to a \fIfile\fR instead of stdout.
.HP
\fB\-lo\fR or \fB\-\-log\-overwrite\fR
Overwrite the log file if it already exists.
.TP
\fB\-L\fR or \fB\-\-language\fR [\fIEN\fR]
Fetch subtitles in a particular language. You have to specify two-letter code.
.TP
\fB\-M\fR or \fB\-\-move\fR
In the case of \fB\-s\fR option, move files rather than copy.
.TP
\fB\-n\fR or \fB\-\-nfo\fR
Create a file containing information concerning subtitles. Only supported when combined with \fB\-\-id\fR \fINapiProjektPython\fR or \fINapiProjekt\fR
.TP
\fB\-p\fR or \fB\-\-pass\fR [\fIpassword\fR]
Set the password for the user that was set via the \fI--user\fR option.
.TP
\fB\-S\fR or \fB\-\-script\fR [\fIscript_path\fR]
Call a script after downloading subtitles. The path to the subtitle file will be passed as an argument 
.TP
\fB\-s\fR or \fB\-\-skip\fR
Don't download if the subtitles are already downloaded.
.TP
\fB\-u\fR or \fB\-\-user\fR \fIlogin\fR
Set the username.
.TP
\fB\-v\fR or \fB\-\-verbosity\fR [\fI0\fR, \fI1\fR, \fI2\fR, \fI3\fR]
Set the verbosity level, \fI0\fR for silent, \fI3\fR for debug.
.TP
\fB\-\-stats\fR
Show statistics.
.TP
\fB\-d\fR or \fB\-\-delete\-orig\fR
Delete the original file.
.TP
\fB\-f\fR or \fB\-\-format\fR
Convert subtitles to this format. It requires \fBsubotage\fR.
.TP
\fB\-P\fR or \fB\-\-pref\-fps\fR [\fItool\fR]
Use the preferred tool as an FPS detector.
.TP
\fB\-o\fR
\fB\-\-orig\-prefix\fR
Set prefix for the original file before conversion, defaults to \fIORIG_\fR .
\fB\-\-conv\-abbrev\fR <string>
Add a string before the extension while converting file formats.
.SH EXAMPLES
.PP
Here are some examples:
.TP
\fBnapi\fR \fIfilm.avi\fR
Download subtitles for \fIfilm.avi\fR .
.TP
\fBnapi\fR \fB\-c\fR \fIfilm.avi\fR
Download subtitles and a cover for \fIfilm.avi\fR .
.TP
\fBnapi\fR \fB\-u\fR \fIfoo\fR \fB\-p\fR \fIbar\fR \fB\-c\fR \fIfilm.avi\fR
Download subtitles and a cover for \fIfilm.avi\fR as a user \fIfoo\fR using password \fIbar\fR .
.TP
\fBnapi\fR \fI*\fR
Search for video files in the current directory (and its subdirectories) and try to match and download subtitles for those files.
.TP
\fBnapi\fR \fI*.avi\fR
Search only for \fIavi\fR files.
.TP
\fBnapi\fR \fImovie_dir\fR
Search for movies in the \fImovie_dir\fR directory and its subdirectories.
.TP
\fBnapi\fR \fB\-f\fR \fIsubrip *\fR
Download subtitles for every movie file found in the current directory (and its subdirectories) and convert them to the \fIsubrip\fR format.
.SH "SEE ALSO"
The full documentation for \fBnapi\fR is maintained as a Texinfo manual.  If the \fBinfo\fR and \fBnapi\fR programs are properly installed in your system, the command \fBinfo napi\fR should give you access to the complete manual.
.SH AUTHOR
.PP
\fBnapi\fR was written by Tomasz Wisniewski aka DAGON <tomasz.wisni3wski@gmail.com>
.PP
This manual page was originally written for the Debian GNU/Linux system by Mikhail Morfikov <mmorfikov@gmail.com>.
