.\" man page originally for the Debian/GNU Linux system
.TH SUBOTAGE "1" "February 2015" "subotage: 1.3.4" "User Commands"
.SH NAME
subotage \- universal subtitle format converter
.SH DESCRIPTION
subotage \fB\-i\fR [\fIinput_file\fR] \fB\-o\fR [\fIoutput_file\fR] [options]
.PP
Options:
.TP
\fB\-i\fR or \fB\-\-input\fR [\fIinput_file\fR]
Input file (required).
.TP
\fB\-o\fR or \fB\-\-output\fR [\fIoutput_file\fR]
Output file (required).
.TP
\fB\-if\fR or \fB\-\-input\-format\fR [\fIformat\fR]
Enforce the input file format. It'll be automatically detected if this option isn't specified.
.HP
\fB\-of\fR or \fB\-\-output\-format\fR [\fIformat\fR]
The output format (\fIsubrip\fR by default).
.TP
\fB\-fi\fR or \fB\-\-fps\-input\fR [\fIfps\fR]
FPS for the input file (important only in the case of microdvd format), defaults to 0.
.TP
\fB\-fo\fR or \fB\-\-fps\-output\fR [\fIfps\fR]
FPS  for the output file (important only in the case of microdvd format), defaults to 0.
.TP
\fB\-l\fR or \fB\-\-lasting\-time\fR [\fItime in ms\fR]
Period of time (in milliseconds) in which the lines are displayed, defaults to 3000 ms.
.HP
\fB\-gi\fR or \fB\-\-get\-info\fR [\fIinput_file\fR]
Show only information about the input file.
.HP
\fB\-gf\fR or \fB\-\-get\-formats\fR
Show only supported formats.
.HP
\fB\-gl\fR | \fB\-\-get\-formats\-long\fR
Show supported formats including some information about them.
.TP
\fB\-v\fR or \fB\-\-verbosity\fR [\fI0, 1, 2, 3\fR]
Verbosity level, \fI0\fR - silent, \fI3\fR the most verbose.
.SS Supported formats:
.IP
\fImicrodvd\fR \- {start}{stop} - format based on frames. Uses given frame rate, 0 by default.
.IP
\fImpl2\fR \- [start][stop] format. The unit is time based == 0.1 sec.
.IP
\fIsubrip\fR \- hh.mm.ss,mmm \-> hh.mm.ss,mmm format.
.IP
\fIsubviewer2\fR \- hh:mm:ss:dd,hh:mm:ss:dd format with header. Resolution = 10ms. Header is ignored.
.IP
\fItmplayer\fR \- hh:mm:ss timestamp format without the stop time information. Mostly deprecated.
.SH EXAMPLES
.PP
Here are some examples:
.TP
\fBsubotage\fR \fB-i\fR \fIinput_file.txt\fR \fB-o\fR \fIoutput_file.srt\fR
Convert from microdvd 23.98 fps to subrip. Subrip is default output format so it doesn't have to be specified. The input frame rate is also equal to the default one, so no addition specification in the command line has been made.
.TP
\fBsubotage\fR \fB-i\fR \fIinput_file.txt\fR \fB-fi\fR \fI25\fR \fB-of\fR \fIsubviewer\fR \fB-o\fR \fIoutput_file.sub\fR
Convert from microdvd 25 fps to subviewer.
.TP
\fBsubotage\fR \fB-i\fR \fIinput_file.srt\fR \fB-of\fR \fIfab\fR \fB-o\fR \fIoutput_file.fab\fR
Convert from subrip to fab.
.TP
\fBsubotage\fR \fB-i\fR \fIinput_file.txt\fR \fB-fi\fR \fI25\fR \fB-fo\fR \fI29.98\fR \fB-of\fR \fImicrodvd\fR \fB-o\fR \fIoutput_file.txt\fR
Convert from microdvd 25 fps to microdvd 29.98 fps.
.SH "SEE ALSO"
The full documentation for \fBsubotage\fR is maintained as a Texinfo manual. If the \fBinfo\fR and \fBsubotage\fR programs are properly installed in your system, the command \fBinfo subotage\fR should give you access to the complete manual.
.SH AUTHOR
.PP
\fBsubotage\fR was written by Tomasz Wisniewski aka DAGON <tomasz.wisni3wski@gmail.com>
.PP
This manual page was originally written for the Debian GNU/Linux system by Mikhail Morfikov <mmorfikov@gmail.com>.
